PeriodicVariables2 Noelle PR
arcana-lab/noelle pull request #165
Opened 2024-09-26 15:09 UTC by dmdlott

PeriodicVariableSCC now more carefully chooses its accumulator.

Also adds detection for 2-phis-case Periodic Variable SCC, provided only one of the two phis has SCC-external users.

This PR is a sister to the GINO PR fixing PeriodicVariables2.

2024-09-29 23:25 UTC, scampanoni commented on src/core/loop_scc_attributes/src/PeriodicVariableSCC.cpp
> +  // DDLOTT: the algorithm for determining the accumulator in
This comment is confusing. The class SingleAccumulatorRecomputableSCC is meant to handle a single-accumulator SCC as the name suggests. So it's strange to have a comment in this class saying the algorithm included within is not sufficient for 2-phis (hence multiple accumulators).

2024-09-29 23:26 UTC, scampanoni commented on src/core/loop_scc_attributes/src/PeriodicVariableSCC.cpp
> +  // to have non-phi users, but the algorithm can't deal with picking the phi
I didn't get this comment. All phis have users.

2024-09-29 23:26 UTC, scampanoni commented on src/core/loop_scc_attributes/src/PeriodicVariableSCC.cpp
> +    // DD: responsibility for this being a PHINode lies with the SCCDAGAttrs
Please remove "DD".

I didn't get this comment as well.

2024-09-29 23:27 UTC, scampanoni commented on src/core/loop_sccdag_attributes/src/SCCDAGAttrs.cpp
> +      // DDLOTT Sep/3/2024: SingleAccumulatorRecomputableSCC's accumulator
Please remove "DDLOT" and the date.

2024-09-29 23:28 UTC, scampanoni commented on src/core/loop_sccdag_attributes/src/SCCDAGAttrs.cpp
> +      // DDLOTT Sep/3/2024: SingleAccumulatorRecomputableSCC's accumulator
I didn't get this comment

2024-09-29 23:28 UTC, scampanoni commented on src/core/loop_sccdag_attributes/src/SCCDAGAttrs.cpp
> +  // DD: whether or not a variable is periodic is not decidable.
Please remove "DD"

2024-09-29 23:28 UTC, scampanoni commented on src/core/loop_sccdag_attributes/src/SCCDAGAttrs.cpp
> +  // DD: whether or not a variable is periodic is not decidable.
What is the purpose of this comment?

2024-09-29 23:28 UTC, scampanoni commented on src/core/loop_sccdag_attributes/src/SCCDAGAttrs.cpp
> +    Value *accumulator; // should be nullptr at return unless the Periodic
Please initialize it to nullptr

2024-09-29 23:28 UTC, scampanoni commented on src/core/loop_sccdag_attributes/src/SCCDAGAttrs.cpp
> +    // DD: we want to capture a case where we have phi1=(ph, -x)(latch, phi2)
Remove "DD"

2024-09-29 23:29 UTC, scampanoni commented on src/core/loop_sccdag_attributes/src/SCCDAGAttrs.cpp
> +    // DD: we want to capture a case where we have phi1=(ph, -x)(latch, phi2)
Please expand the code in the comment aiming for higher precision.

2024-09-29 23:30 UTC, scampanoni requested changes
The code looks good to me (great job!).

The comments need to improve before we merge this PR.

2024-10-07 18:59 UTC, dmdlott commented
@scampanoni bumping this

2024-10-07 22:06 UTC, scampanoni commented on src/core/loop_scc_attributes/src/PeriodicVariableSCC.cpp
> +       * is in GINO) is fully compatible with that representation.
We should not reference code that builds upon NOELLE.

2024-10-07 22:08 UTC, scampanoni requested changes

2024-10-07 22:08 UTC, scampanoni commented on src/core/loop_sccdag_attributes/src/SCCDAGAttrs.cpp
> +<<<<<<< HEAD
Please delete this

2024-10-07 22:08 UTC, scampanoni commented on src/core/loop_sccdag_attributes/src/SCCDAGAttrs.cpp
> +>>>>>>> 483b2ea3fe44c205a5f722d79483f07f562938a9
Please delete this

2024-10-07 22:08 UTC, scampanoni commented on src/core/loop_sccdag_attributes/src/SCCDAGAttrs.cpp
> +<<<<<<< HEAD
You probably merged without checking these files

2024-10-07 22:08 UTC, scampanoni commented on src/core/loop_sccdag_attributes/src/SCCDAGAttrs.cpp
> +<<<<<<< HEAD
Problem with merging

2024-10-07 22:08 UTC, scampanoni commented on src/core/loop_sccdag_attributes/src/SCCDAGAttrs.cpp
> +>>>>>>> 483b2ea3fe44c205a5f722d79483f07f562938a9
Problem with merging

2024-10-07 22:08 UTC, scampanoni commented on src/core/loop_sccdag_attributes/src/SCCDAGAttrs.cpp
> +>>>>>>> 483b2ea3fe44c205a5f722d79483f07f562938a9
Problem with merging

2024-10-07 22:08 UTC, scampanoni commented on src/core/loop_sccdag_attributes/src/SCCDAGAttrs.cpp
> +<<<<<<< HEAD
Problem with merging

2024-10-07 22:08 UTC, scampanoni commented on src/core/loop_sccdag_attributes/src/SCCDAGAttrs.cpp
> +>>>>>>> 483b2ea3fe44c205a5f722d79483f07f562938a9
Problem with merging

2024-10-08 00:07 UTC, merged